package com.sujal;

public class Tester {

	public static void main(String[] args) {

		
		Trip trip1 = new Trip("Premium", 20000.0, 10);
        Trip trip2 = new Trip("Premium", 20000.0, 10); 
        Trip trip3 = new Trip(15);
			
        //toString() method is auto generated by the record
        System.out.println("Trip 1 :" +trip1); 
        System.out.println("Trip 2 : "+trip2); 
        System.out.println("Trip 3 : "+trip3);

        //hashCode() method is auto generated by the record
        System.out.println("\nHashcode of trip1 : "+trip1.hashCode()); 
		System.out.println("Hashcode of trip2 : "+trip2.hashCode());
		System.out.println("Hashcode of trip3 : "+trip3.hashCode());
        
		//equals() method is auto generated by the record
		System.out.println("\nChecking for equality of trip1 and trip2 objects : "+trip1.equals(trip2));
		System.out.println("Checking for equality of trip1 and trip3 objects : "+trip1.equals(trip3));
		
		
		//static variables and methods can be accessed directly using the record name
		System.out.println("\nBase discount : " +Trip.discount); 
		System.out.println("The total cost for Trip 1 is : " +Trip.applyOffer(trip1.noOfDays(), trip1.fare()));
		
		
		
	}

}
